REDIS_HOST = "localhost"
REDIS_PORT = 6379
REDIS_DB = 0

IMAGE_HEIGHT = 300
IMAGE_WIDTH = 300
IMAGE_CHANS = 3

BATCH_SIZE = 32
IMAGE_DTYPE = "float32"

IMAGE_QUEUE = "image_queue"
SERVER_SLEEP = 0.25
CLIENT_SLEEP = 0.25
